package com.example.gridpart;

import android.support.annotation.StringRes;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {
    List<Book> lstBook;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        lstBook = new ArrayList<>();
        lstBook.add(new Book("Diaphragm Breathing","Benefits:\n"+"A few minutes of this exercise will help you feel grounded and relaxed\n","Steps:\n"+ "1. Get comfortable in your prefered meditaon posture \n2. Put one palm on your upper chest and the other over your navel.\n3. Breathe in slowly through your nose - noce the stomach moving out. The hand on your chest remains sll.\n4. Breathe out fully and then a lile bit more. Ensure that the hand on your upper chest is sll\n5. Pause for 2 seconds\n6. Allow the air to naturally ﬂow in again \n7.  Imagine your muscles are relaxing with every exhalaon.\n8. Slowly and calmly repeat this cycle a few mes\n",R.drawable.a000));
        lstBook.add(new Book("Stomach Breathing","Benefits:\n"+" Stomach breathing can help you feel calm and better\n","Steps:\n"+"1. Get comfortable in your prefered meditaon posture \n2. Close your eyes and focus on your breathing. Don’t force it, just observe it come in and go out.\n 4. When you breathe in, imagine that your lungs are in your stomach, under your navel.\n 5. Imagine the feeling of the warm air going all the way down to the stomach.\n 6. Follow your breath back up again, from your stomach and out through your nose.\n 7. Repeat the exercise.\n",R.drawable.a000));
        lstBook.add(new Book("Balloon Breathing","Benefits:\n"+" Balloon breathing can help you break away from stress and anxiety\n","Steps:\n"+" 1. Get comfortable in your prefered meditaon posture \n2. Bring your aenon on your breathing. Don’t force it, just observe it come in and go out. \n4. Now imagine that the air you inhale enters a balloon \n5. Pick a color for the balloon- let it be a happy color \n6. Take a deep breath through your nose and imagine the balloons expanding \n7. Breathe out and imagine the balloon deﬂate. Notice how it feels. \n8. Don’t force it. If you are comfortable keep adding balloons as you repeat the exercise\n",R.drawable.a000));
        lstBook.add(new Book("Ribcage Breathing","Benefits:\n"+" This form of deep breathing exercise helps you relax and focus\n","Steps:\n"+"1. Get comfortable in your prefered meditaon posture \n2. Bring your aenon on your breathing. Don’t force it, just observe it come in and go out. \n4. Now imagine that the air you inhale enters a balloon \n5. Pick a color for the balloon- let it be a happy color \n6. Take a deep breath through your nose and imagine the balloons expanding \n7. Breathe out and imagine the balloon deﬂate. Noce how it feels. \n8. Don’t force it. If you are comfortable keep adding balloons as you repeat the exercise\n",R.drawable.a001));
        lstBook.add(new Book("Body Scan","Benefits:\n"+" Learn to be fully present and awake to your physical sensations\n","Steps:\n"+" 01. Choose a comfortable meditaon posture \n02. Anchor your focus on your breathing. Don’t force it, just observe it come in and go out. \n03. Noce the sensaons and become aware of the feelings  you are experiencing \n04. Start with your le foot. Focus your aenon on how it feels \n05. Connue up the body, spending 30 seconds to focus on each part of the body \n06. Allow each part to be as it is ,just noce the sensaons and the feeling \n07. You may consider appreciang each part – say ‘Thank you’ to that part for how it is supporng you. \n08. Slowly and steadily move up the body, scanning up to your head \n09. Once you have scanned up to your head  bring your aenon back to your breathing 10. Finish the body scan by focusing on the way the whole body is feeling \n",R.drawable.a01));
        lstBook.add(new Book("Retreat Breathing","Benefits:\n"+" Few minutes of this exercise can increase self- awareness and enhance your concentration ","Steps:\n"+" 1. Get comfortable in your meditaon posion \n2. Relax and focus on your breathing \n3. Bring your awareness to the sounds you hear. \n4. Try and idenfy the sounds and then let it fade away from your consciousness \n5. Slowly bring your focus to the room you are presently in. What sounds can you hear in the room? \n6. Slowly bring your awareness closer to you, just around your body. Become aware of the space, the sound of your breathing, heartbeat.\n 8. Stay in the moment for a few seconds and become aware of the sensaons and feelings you are experiencing. \n9. In case your mind wanders, bring the focus back to the breathing\n",R.drawable.a00));
        lstBook.add(new Book("Grounding Self","Benefits:\n"+" Feel grounded and relaxed with few minutes of this exercise","Steps:\n"+" 01. Get comfortable in your meditaon posion \n02. Relax and focus on your breathing \n03. Slowly, with the next breath bring your awareness to your feet \n04. Noce for the feelings and sensaons \n05. As you concentrate, imagine your feet becoming heavy and secure on the ﬂoor. 06. Now as you connue breathing, imagine and feel the long roots coming out of your feet and going deep into the ground.\n 08. Stay with the feeling for a while \n09. As you focus on your feet, slowly feel yourself sinking back into your whole body again. \n10. Noce which parts of you are touching the ﬂoor, chair or bed and realize how solid and heavy they feel. \n11. Slowly as you breathe let the image of the growing roots fade away. \n12. Become aware of how diﬀerently you feel now – You are grounded \n",R.drawable.a2));
        lstBook.add(new Book("Cleansing Sanctuary","Benefits:\n"+" Use this exercise to walk yourself out of bad moods and unwanted energies\n","Steps:\n"+"01. Get comfortable in your meditaon posion \n02. As you pay aenon to the breathing, imagine what is most comforng and cleansing for you (warm sunshine or may be a so gentle rain). \n04. Give yourself some me to think create and reﬂect about it. Strengthen your relaonship with it by making it as vivid as possible. \n06. Connue to breathe as you process the image in your mind \n08. Become aware of how you are feeling.  Once you feel the image is vivid and powerful, slowly place yourself in it.\n 09. Imagine a gentle smile appearing on your face. \n10. Hold on to that feeling of cleansing and comfort.  \n 11. When you are ready, return to normal breathing and as you do so let the image fade away.\n 12. Become aware of how diﬀerently you feel now – are you feeling calm and refreshed",R.drawable.a3));
        lstBook.add(new Book("Mountain Meditation","Benefits:\n"+" Relax and recharge yourself with a few minutes of this exercise\n","Steps:\n"+"01. Get comfortable in your meditaon posion \n02. Focus on the area where the breathing is more vivid and tangible. \n03. Now imagine an image of the most magniﬁcent mountain. Let it gradually come into greater focus. \n04. Noce how massive it is, how solid, how unmoving, how beauful it is. \n05. When you feel ready, bring the mountain into your own body so that your body and the mountain in your mind’s eye become one. Resonate with the massiveness, sllness and majesty of the mountain. \n06. With each breath, make the image more vivid ll you become a breathing mountain \n07. Connue breathing and keep reminding yourself that you are the mountain and start to resonate with its strength and stability\n 08. Stay with the feeling for some me\n 09. When you are ready, return to normal breathing and as you do so let the image fade away. 10. Become aware of how diﬀerently you feel now – are you feeling refreshed and strong\n",R.drawable.a4));
        lstBook.add(new Book("Comparing Emotions","Benefits:\n"+" Use this exercise to fix your mood and to feel positive ","Steps:\n"+"01.Sit in a comfortable, meditaon posion \n02. Focus on your breathing. \n03. As you concentrate, think of a diﬃcult or stressful situaon. \n04. Become aware of the emoons and stay with that feeling for some me. \n05. Noce how it is aﬀecng your body, your breathing and your mental emoonal state. \n06. Now choose to let it go. \n07. Now repeat the same, now with something that makes you feel really good.  Sink into this emoon \n08. Stay with that feeling for some me. \n09. Noce the smile coming back to your face. Let it become a big, generous smile. Noce the changes you feel inside: physically, emoonally and mentally. \n10. Allow the feeling of wellbeing to increase and swell inside and around you. \n11. Enjoy the moment \n12. When you are ready, return to normal breathing 14. Become aware of how diﬀerently you feel now – You are posive and happy ",R.drawable.a5));
        lstBook.add(new Book("Letting Your Thoughts Go!","Benefits:\n"+" Use this technique to overcome anxiety and feel confident\n","Steps:\n"+" 01. Sit in a comfortable, meditaon posture \n02. Focus on your breathing. Don’t force it let it come and go naturally. \n03. As you concentrate, think of the thoughts that is worrying you and causing anxiety. \n04. Write them virtually in the air. \n05. Now imagine that thought to pass away on a conveyer belt  to a very faraway ‘no man’s’ land.\n 06. Do not ﬁght, suppress the thoughts that are troubling you. \n07. Simply allow them to come and go. Stay with that feeling for some me. \n08. Now when you are ready idenfy acvies that you can turn to when you want to switch oﬀ from worrying 09. Crystalize that acvity in your mind and make it vivid. Now slowly put yourself in that acvity. \n10. Noce the feeling that you are experiencing while doing that acvity. Noce how it is aﬀecng your body \n11. Now choose to let that also go. 12. Repeat this exercise \n13. When you are ready open your eyes and become aware of how diﬀerently you feel now\n",R.drawable.a6));
        lstBook.add(new Book("Forgiveness Meditation","Benefits:\n"+" Use this technique to breakthrough toxic situations\n","Steps:\n"+" 01. Sit comfortably in a meditaon posture \n02. Bring awareness  to your breath \n03. Bring your awareness, to the image of the individual that disturbed you or caused you hurt \n04. With the next breath consciously say ' I forgive you and soen toward that person. \n05. Imagine the person coming into your heart just for now as you breathe in. Hold him/her there for a moment, staying present with that person, feeling forgiveness \n06. Now let that person go, Be aware of yourself again \n07. Repeat the same  with someone whom you have harmed in some way and mindfully, connuing breathing ask for forgiveness. Open your heart to this person and imagine him opening his heart to you. \n08. Breathing in, and breathing out, slowly let that image fade away \n09. To conclude, now, imagine your own image, look at yourself and say “I forgive you for whatever you feel you’ve done. \n10. Feel the sensaon of opening your heart to yourself, Allow the sensaon of forgiveness to spread between you and your image \n11. Allow this feeling to grow and expand, breathing in, breathing out, relaxing.  When you are ready open your eyes ",R.drawable.a7));
        lstBook.add(new Book("Mindful Eating","Benefits:\n"+" Improves digestive functioning and reduces overeating ","Steps:\n"+" 1. Sit comfortably with your back straight and close your eyes \n2. Bring awareness ﬁrst to the sounds you hear and then to your breath \n3. With your awareness, choose a piece of food. Try something like a nut, apple or chocolate \n4. Mindfully look at the food, observe and admire the shape, colour and texture \n5. Place the food on your tongue and noce how it feels and the response of your salivary glands\n 6. Next slowly bite into the food. Mindfully chew it nocing the sound, texture and feeling \n7. Actually take me to noce the sensaon of the food as you swallow the food \n8. Now in your mind say the name of the food, acknowledge it and be grateful\n",R.drawable.a8));
        lstBook.add(new Book("Overcoming Craving","Benefits:\n"+" Reduce overeating with this exercise ","Steps:\n"+ "01. Sit comfortably in a meditaon posture \n02. Bring awareness ﬁrst to the sounds you hear and then  to your breath \n03. As you focus on your breathing, think about your cravings. Recognize it as an urge. Do not try to change it or get rid of it. \n04. Use your imaginaon to give the urge a physical form and let it gradually come into greater focus. \n05. Stay with this image for a while and make this image as vivid and strong as possible \n06. With ease slowly loose the ﬁxaon. Imagine it to  dri away from you and fade away to a distance. Stay with that moment for some me. \n07. Bring focus back to your breathing and as you do so slowly think about all the good intenons and posives about overcoming the urge. \n08. Here also give these good intenons a form and imagine in coming towards you, each step making it larger and more vivid.\n 09. Build in the intensity and stay with that image. Reﬂect on how it makes you feel. Slowly start to resonate with that feeling \n10. When you are ready slowly open your eyes and become aware of the moment.\n",R.drawable.a9));
        lstBook.add(new Book("Mindful Smiling ","Benefits:\n"+" Feel positive and appreciate the wonderful life you have\n","Steps:\n"+" 01. Get to a meditaon posture \n02.  Focus on your breath. Don’t force it let it come and go naturally. \n03. As you concentrate, think about what makes you smile.\n 04. Focus on the image of yourself smiling.  \n05. Sink into the emoon associated with that situaon \n08. Stay with that feeling for some me. \n09. Now reﬂect upon how you might capture that smile or memory, a photo, a painng, a piece of clothing, a scent. \n10. As you store up these items in your thoughts, resolve that you will draw them close to you when you ﬁnish your meditaon or aer you go back home today. \n11. Imagine the item being in a special place close to you and reﬂect on how that makes you feel.\n 13. Are you smiling as you do so? \n14. When you are ready, refocus your thoughts on where you are right now\n",R.drawable.a10));
        lstBook.add(new Book("Mindful Reflective Listening","Benefits:\n"+"Improve your listening skills with this exercise","Steps:\n"+"cSit in a comfortable, upright posion and close your eyes \n02. Focus on your breathing. Don’t force it let it come and go naturally. \n03. Noce for the feelings and sensaons \n04. When you are ready open your eyes and acknowledge your partner for this exercise. \n05. Invite the partner to speak on the topic of their choice \n06. While the partner is speaking, you are requested to listen to him/her intently\n 07. Reﬂect on the choice of words, the emoons that you can feel. \n08. Once the speaker ﬁnishes, Share what you have heard \n09. Noce what you are saying, is it a mere paraphrase? What do you feel when you are retelling the story? How do you feel about the person/partner now \n10. Become aware of these feeling and emoons \n11. Now switch roles and repeat the exercise\n",R.drawable.a11));
        lstBook.add(new Book("Having patience ","Benefits:\n"+" Improve your listening skills with this exercise","Steps:\n"+" 01. Sit in a comfortable, upright posion and close your eyes \n02. Focus on your breathing. \n03. Noce for the feelings and sensaons \n04. As you concentrate, draw up the diﬀerent tasks that you need to get done today. Idenfy each of them \n05. Recognize the urgency that you are feeling to get into acon. Stay with that feeling \n06. Slowly with the next breath imagine a blank canvas in front of you, there is also a supply of colours. Make this as vivid as possible, recognize the colours in front of you, and imagine the feeling of the brush. \n07. You are now about to paint the most beauful rose.\n 08. Resist the urge to get in to acon. \n09. Slowly let the image of the rose come to life. Imagine the colour, the folds of the petals, the spikes of the thorns, the feel of the stem \n10. Now with the next breath start to paint the rose part by part, the stem, leaves, the petals and slowly visualize it come to life \n11. As you do so stay with the painng step by stem and idenfy your emoons that you are experiencing seeing the ﬂower come to life.\n12. Once your ﬂower is ready, look at it and resonate with its beauty 13. When you’re ready, open your eyes and bring ring your aenon back into the room.\n",R.drawable.a12));
        lstBook.add(new Book("Just Worrying Labelling Technique\n","Benefits:\n"+"Identify anxiety and use this technique to overcome it\n","Steps:\n"+" 01. Sit in a comfortable, upright posion and close your eyes \n02. Focus on your breathing. Become aware of the breath going in and out.\n 03. Don’t force it let it come and go naturally. \n04. Noce for the feelings and sensaons \n05. As you concentrate, draw up the diﬀerent things that are worrying you \n06. Idenfy each one of them and if ok with you give it a form \n07. Then with the next breath label the worry as ‘Just worrying’ and imagine pung into a big bowl. Bring the aenon back to the breath and change the subject of their thinking.\n 08. Repeat this with all your worries one aer the other and each me.\n 09. Do this eﬀortlessly, each me focus on your breath. \n10. When you are ready open your eyes and reﬂect on the current feeling.\n",R.drawable.a13));


        RecyclerView myrv = findViewById(R.id.recyclerview_id);
        RecyclerViewAdapter myAdapter = new RecyclerViewAdapter(this,lstBook);
        myrv.setLayoutManager(new GridLayoutManager(this,2));
        myrv.setAdapter(myAdapter);


    }
}
